"""
Project Builder — Phase 3 Module
Creates the full project scaffold so the generated template is a
ready-to-run Vite + React + Tailwind project.
"""
import json, os, re, logging, textwrap

logger = logging.getLogger(__name__)

class ProjectBuilder:
    async def build(self, spec: dict, output_dir: str) -> dict:
        tname = self._slugify(spec.get("template_type", "template"))
        pdir = os.path.join(output_dir, tname)
        os.makedirs(pdir, exist_ok=True)
        files = []

        # package.json
        with open(os.path.join(pdir, "package.json"), "w") as f:
            json.dump(self._pkg(tname), f, indent=2)
        files.append("package.json")

        # vite config
        with open(os.path.join(pdir, "vite.config.js"), "w") as f:
            f.write("import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins: [react()], server: { port: 3000, open: true } });\n")
        files.append("vite.config.js")

        # index.html
        title = tname.replace("-"," ").title()
        with open(os.path.join(pdir, "index.html"), "w") as f:
            f.write(f'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8"/>\n<meta name="viewport" content="width=device-width,initial-scale=1.0"/>\n<meta name="description" content="{title}"/>\n<title>{title}</title>\n<link rel="preconnect" href="https://fonts.googleapis.com"/>\n<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"/>\n</head>\n<body>\n<div id="root"></div>\n<script type="module" src="/src/main.jsx"></script>\n</body>\n</html>\n')
        files.append("index.html")

        # src dirs
        src = os.path.join(pdir, "src")
        for sub in ["components","pages","styles","assets"]:
            os.makedirs(os.path.join(src, sub), exist_ok=True)
        os.makedirs(os.path.join(pdir, "public"), exist_ok=True)

        # main.jsx
        with open(os.path.join(src, "main.jsx"), "w") as f:
            f.write("import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './styles/tailwind.css';\nReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);\n")
        files.append("src/main.jsx")

        # App.jsx
        with open(os.path.join(src, "App.jsx"), "w") as f:
            f.write("import React from 'react';\nimport LandingPage from './pages/LandingPage';\nexport default function App() { return <LandingPage />; }\n")
        files.append("src/App.jsx")

        # .gitignore & README
        with open(os.path.join(pdir, ".gitignore"), "w") as f:
            f.write("node_modules/\ndist/\n.env\n")
        with open(os.path.join(pdir, "README.md"), "w") as f:
            f.write(f"# {title}\n\nAuto-generated by MCP Brain Template Generator.\n\n```bash\nnpm install && npm run dev\n```\n")
        files += [".gitignore", "README.md"]

        logger.info("Scaffold created: %s (%d files)", pdir, len(files))
        return {"project_dir": pdir, "template_name": tname, "files_created": files}

    def _pkg(self, name):
        return {
            "name": name, "private": True, "version": "1.0.0", "type": "module",
            "scripts": {"dev": "vite", "build": "vite build", "preview": "vite preview"},
            "dependencies": {"react": "^18.3.0", "react-dom": "^18.3.0", "framer-motion": "^11.0.0", "gsap": "^3.12.5", "lenis": "^1.1.13"},
            "devDependencies": {"@vitejs/plugin-react": "^4.3.0", "vite": "^5.4.0", "tailwindcss": "^3.4.0", "autoprefixer": "^10.4.0", "postcss": "^8.4.0"},
        }

    @staticmethod
    def _slugify(t):
        return re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-") or "template"
